version: "3.7"
services:
  mysql-service:
    image: computer-services-mysql
    networks:
      - spring-boot-mysql-network
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=phongtt
      - MYSQL_DATABASE=computer_services
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "1025:1025"
    networks:
      - spring-boot-mysql-network
    depends_on:
      - mysql-service
networks:
  spring-boot-mysql-network:
    driver: bridge
