spring:
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/computer_services?serverTimezone=Asia/Ho_Chi_Minh&autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8"
    username: "computer_services"
    password: "phongtt"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
server:
  port: 1025

fatstack:
  app:
    jwtSecret: fatStackSecretKey
    jwtExpirationMs: 86400000

